### ISSUE TITLE
Cambios Software de reservas

### ISSUE THREAD

**Issue by leoramz** [terrill021/sisgraeserver#2]
Alejandro,

Los siguientes son detalles que se han dado en el periodo del prueba del software Sisgrae:
1. Al momento de pasar un reserva a Realizadas el contador no reinicia el contador de reservas disponibles, solo cuando se cancela.
2. En el momento el software cuenta con seis salas para préstamo: 2 de 30 equipo, 2 de 15 equipos, y dos para un 1 equipo cada uno, es posible que priorice por numero solicitado, es decir: Si es coges entre 2 y 15 que muestre los salones que tiene capacidades máximo de 15 computadores, si son mas de 30 que muestre principalmente los de 30 y si es 1 solo las salas con capacidad de un solo computador.

Cualquier comentario me haces saber.

Saludos y muchas gracias.

**Comment by terrill021** [comment]
1. Corregido. El cambio de hace visible cuando el usuario vuelva a inciar sesión.

2. En respuesta a esta sugerencia, se debe tener en cuenta que los usuarios no saben que sala estan reservando, el caso propuesto tambien puede llevar al echo de que si escoges entre 2 y 15 los salones con esta capácidad esten todos ocupados por lo que no hay disponibilidad, pero si hay un salon mas grande el cual esta desocupado y no puede ser reservado.

**Comment by leoramz** [comment]
Buen dia alejandro.

Tienes toda la razon, de esta manera hay mas disponibilidad en ese ejemplo, pero en caso que soliciten salones con menos de 15 computadores y escojen los que tienen capacidad para 30 PCs y luego a esa misma hora solicitan un personal con un numero superior a 15 PCs las salas que están disponibles no cumplen esas especificaciones por tanto no pueden reservar, en ese caso como se hace, no podría ser el software optimo en ese sentido?

Man cualquier cosa me dices o me avisas para llamarte.

Gracias
